# uses Swiftenv, xcodebuild and xcpretty to test Swift snapshots
# https://swiftenv.fuller.li/en/latest/integrations/travis-ci.html
os:
- osx
# to test for Swift under Linux uncomment the following 3 lines:
#- linux
#language: generic
#dist: trusty
sudo: required
xcode_project: SwiftyBeaver.xcodeproj
xcode_scheme: SwiftyBeaver (iOS)
osx_image: xcode8
xcode_sdk: iphonesimulator10.0
#env:
#- SWIFT_VERSION=swift-DEVELOPMENT-SNAPSHOT-2016-05-31-a # CHANGE THIS ON NEW VERSIONS
before_install:  # to fix xctool issue since Xcode 7.3
- gem install xcpretty
#install:
#- eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)"
script:
  - swift build
  - set -o pipefail  # required to let xcpretty use the same exit code like xcodebuild
  - xcodebuild TOOLCHAINS=swift -project SwiftyBeaver.xcodeproj -scheme "SwiftyBeaver (iOS)" -destination name="iPhone 6" -destination name="iPhone 6" test | xcpretty -c
