# uses Swiftenv, xcodebuild and xcpretty to test Swift snapshots
# https://swiftenv.fuller.li/en/latest/integrations/travis-ci.html
os:
- osx
# to test for Swift under Linux uncomment the following 4 lines:
#- linux
#language: generic
sudo: required
#dist: trusty
xcode_project: SwiftyBeaver.xcodeproj
xcode_scheme: SwiftyBeaver (iOS)
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
env:
- SWIFT_VERSION=DEVELOPMENT-SNAPSHOT-2016-05-09-a  # CHANGE THIS WHEN NEEDED
before_install:  # to fix xctool issue since Xcode 7.3
- gem install xcpretty
#- brew uninstall xctool && brew install --HEAD xctool
install:
- eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)"
script:
  - swift build
  - set -o pipefail  # required to let xcpretty use the same exit code like xcodebuild
  - xcodebuild TOOLCHAINS=swift -project SwiftyBeaver.xcodeproj -scheme "SwiftyBeaver (iOS)" -destination name="iPhone 6" -destination name="iPhone 6" build test | xcpretty -c
  #- xctool -project SwiftyBeaver.xcodeproj -scheme SwiftyBeaver\ \(iOS\) -sdk iphonesimulator9.3 build test
